### ISSUE TITLE
開発用サーバ起動しない // ERROR  Builder is not a constructor

### ISSUE THREAD

**Issue by getty708** [gdsc-osaka/gonuxt#15]
実行環境は、 bash on git

```bash
$ node --version
v17.5.0

$ npm run dev

> nuxt-templates@1.0.0 dev
> nuxt

i Listening on: http://localhost:3000/

 ERROR  Builder is not a constructor

  at NuxtCommand.getBuilder (node_modules\@nuxt\cli\dist\cli-index.js:487:12)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object._buildDev (node_modules\@nuxt\cli\dist\cli-dev.js:104:21)
  at async Object.startDev (node_modules\@nuxt\cli\dist\cli-dev.js:65:7)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-dev.js:52:5)
  at 
```

**Comment by getty708** [comment]
@k-kuboo 
まず、次の設定を確認してください . Nodeのversionも教えてください。

https://github.com/gdsc-osaka/gonuxt/issues/5

**Comment by getty708** [comment]
v17.5.0 & windows (Power shell) で動作している人を確認

**Comment by getty708** [comment]
適切に #5 のOpenSSLに関する設定をすると解決した。
